var cindex ={
  '가나': 'GH',
  '가봉': 'GA',
  '가이아나': 'GY',
  '감비아': 'GM',
  '건지': 'GG',
  '과들루프': 'GP',
  '과테말라': 'GT',
  '괌': 'GU',
  '그레나다': 'GD',
  '그리스': 'GR',
  '그린란드': 'GL',
  '기니': 'GN',
  '기니비사우': 'GW',
  '나미비아': 'NA',
  '나우루': 'NR',
  '나이지리아': 'NG',
  '남극 대륙': 'AQ',
  '남수단': 'SS',
  '남아프리카 공화국': 'ZA',
  '네덜란드': 'NL',
  '네덜란드령 카리브': 'BQ',
  '네팔': 'NP',
  '노르웨이': 'NO',
  '노퍽섬': 'NF',
  '뉴질랜드': 'NZ',
  '뉴칼레도니아': 'NC',
  '니우에': 'NU',
  '니제르': 'NE',
  '니카라과': 'NI',
  '타이완 (대만)': 'TW',
  '대한민국': 'KR',
  '덴마크': 'DK',
  '도미니카': 'DM',
  '도미니카 공화국': 'DO',
  '독일': 'DE',
  '동티모르': 'TL',
  '디에고 가르시아': 'DG',
  '라오스': 'LA',
  '라이베리아': 'LR',
  '라트비아': 'LV',
  '러시아': 'RU',
  '레바논': 'LB',
  '레소토': 'LS',
  '루마니아': 'RO',
  '룩셈부르크': 'LU',
  '르완다': 'RW',
  '리비아': 'LY',
  '리유니온': 'RE',
  '리투아니아': 'LT',
  '리히텐슈타인': 'LI',
  '마다가스카르': 'MG',
  '마르티니크': 'MQ',
  '마셜 제도': 'MH',
  '마요트': 'YT',
  '마카오(중국 특별행정구)': 'MO',
  '북마케도니아': 'MK',
  '말라위': 'MW',
  '말레이시아': 'MY',
  '말리': 'ML',
  '맨 섬': 'IM',
  '멕시코': 'MX',
  '모나코': 'MC',
  '모로코': 'MA',
  '모리셔스': 'MU',
  '모리타니': 'MR',
  '모잠비크': 'MZ',
  '몬테네그로': 'ME',
  '몬트세라트': 'MS',
  '몰도바': 'MD',
  '몰디브': 'MV',
  '몰타': 'MT',
  '몽골': 'MN',
  '미국': 'US',
  '미국령 버진아일랜드': 'VI',
  '미국령 해외 제도': 'UM',
  '미얀마': 'MM',
  '미크로네시아': 'FM',
  '바누아투': 'VU',
  '바레인': 'BH',
  '바베이도스': 'BB',
  '바티칸 시국': 'VA',
  '바하마 연방': 'BS',
  '방글라데시': 'BD',
  '버뮤다': 'BM',
  '베냉': 'BJ',
  '베네수엘라': 'VE',
  '베트남': 'VN',
  '벨기에': 'BE',
  '벨라루스': 'BY',
  '벨리즈': 'BZ',
  '보스니아 헤르체고비나': 'BA',
  '보츠와나': 'BW',
  '볼리비아': 'BO',
  '부룬디': 'BI',
  '부르키나파소': 'BF',
  '부탄': 'BT',
  '북마리아나제도': 'MP',
  '북한': 'KP',
  '불가리아': 'BG',
  '브라질': 'BR',
  '브루나이': 'BN',
  '사모아': 'WS',
  '사우디아라비아': 'SA',
  '사우스조지아 사우스샌드위치 제도': 'GS',
  '산마리노': 'SM',
  '상투메 프린시페': 'ST',
  '생마르탱': 'MF',
  '생바르텔레미': 'BL',
  '생피에르 미클롱': 'PM',
  '사하라 아랍 민주 공화국 (서사하라)': 'EH',
  '세네갈': 'SN',
  '세르비아': 'RS',
  '세우타 및 멜리야': 'EA',
  '세이셸': 'SC',
  '세인트루시아': 'LC',
  '세인트빈센트그레나딘': 'VC',
  '세인트키츠 네비스': 'KN',
  '세인트헬레나': 'SH',
  '소말리아': 'SO',
  '솔로몬 제도': 'SB',
  '수단': 'SD',
  '수리남': 'SR',
  '스리랑카': 'LK',
  '스발바르제도-얀마웬섬': 'SJ',
  '스웨덴': 'SE',
  '스위스': 'CH',
  '스페인': 'ES',
  '슬로바키아': 'SK',
  '슬로베니아': 'SI',
  '시리아': 'SY',
  '시에라리온': 'SL',
  '신트마르턴': 'SX',
  '싱가포르': 'SG',
  '아랍 에미리트': 'AE',
  '아루바': 'AW',
  '아르메니아': 'AM',
  '아르헨티나': 'AR',
  '아메리칸 사모아': 'AS',
  '아이슬란드': 'IS',
  '아이티': 'HT',
  '아일랜드': 'IE',
  '아제르바이잔': 'AZ',
  '아프가니스탄': 'AF',
  '안도라': 'AD',
  '알바니아': 'AL',
  '알제리': 'DZ',
  '앙골라': 'AO',
  '앤티가 바부다': 'AG',
  '앵귈라': 'AI',
  '어센션 섬': 'AC',
  '에리트레아': 'ER',
  '에스와티니': 'SZ',
  '에스토니아': 'EE',
  '에콰도르': 'EC',
  '에티오피아': 'ET',
  '엘살바도르': 'SV',
  '영국': 'GB',
  '영국령 버진아일랜드': 'VG',
  '영국령 인도양 식민지': 'IO',
  '예멘': 'YE',
  '오만': 'OM',
  '오스트레일리아 (호주)': 'AU',
  '오스트리아': 'AT',
  '온두라스': 'HN',
  '올란드 제도': 'AX',
  '왈리스-푸투나 제도': 'WF',
  '요르단': 'JO',
  '우간다': 'UG',
  '우루과이': 'UY',
  '우즈베키스탄': 'UZ',
  '우크라이나': 'UA',
  '유사 양방향': 'XB',
  '유사 억양': 'XA',
  '이라크': 'IQ',
  '이란': 'IR',
  '이스라엘': 'IL',
  '이집트': 'EG',
  '이탈리아': 'IT',
  '인도': 'IN',
  '인도네시아': 'ID',
  '일본': 'JP',
  '자메이카': 'JM',
  '잠비아': 'ZM',
  '저지': 'JE',
  '적도 기니': 'GQ',
  '조지아': 'GE',
  '중국': 'CN',
  '중앙아프리카 공화국': 'CF',
  '지부티': 'DJ',
  '지브롤터': 'GI',
  '짐바브웨': 'ZW',
  '차드': 'TD',
  '체코': 'CZ',
  '칠레': 'CL',
  '카나리아 제도': 'IC',
  '카메룬': 'CM',
  '카보베르데': 'CV',
  '카자흐스탄': 'KZ',
  '카타르': 'QA',
  '캄보디아': 'KH',
  '캐나다': 'CA',
  '케냐': 'KE',
  '케이맨 제도': 'KY',
  '코모로': 'KM',
  '코소보': 'XK',
  '코스타리카': 'CR',
  '코코스 제도': 'CC',
  '코트디부아르': 'CI',
  '콜롬비아': 'CO',
  '콩고 공화국': 'CG',
  '콩고 민주 공화국': 'CD',
  '쿠바': 'CU',
  '쿠웨이트': 'KW',
  '쿡 제도': 'CK',
  '퀴라소': 'CW',
  '크로아티아': 'HR',
  '크리스마스섬': 'CX',
  '키르기스스탄': 'KG',
  '키리바시': 'KI',
  '키프로스': 'CY',
  '타지키스탄': 'TJ',
  '탄자니아': 'TZ',
  '태국': 'TH',
  '터크스 케이커스 제도': 'TC',
  '터키': 'TR',
  '토고': 'TG',
  '토켈라우': 'TK',
  '통가': 'TO',
  '투르크메니스탄': 'TM',
  '투발루': 'TV',
  '튀니지': 'TN',
  '트리니다드 토바고': 'TT',
  '트리스탄다쿠나': 'TA',
  '파나마': 'PA',
  '파라과이': 'PY',
  '파키스탄': 'PK',
  '파푸아뉴기니': 'PG',
  '팔라우': 'PW',
  '팔레스타인 지구': 'PS',
  '페로 제도': 'FO',
  '페루': 'PE',
  '포르투갈': 'PT',
  '포클랜드 제도': 'FK',
  '폴란드': 'PL',
  '푸에르토리코': 'PR',
  '프랑스': 'FR',
  '프랑스 남부 지방': 'TF',
  '프랑스령 기아나': 'GF',
  '프랑스령 폴리네시아': 'PF',
  '피지': 'FJ',
  '핀란드': 'FI',
  '필리핀': 'PH',
  '핏케언 섬': 'PN',
  '헝가리': 'HU',
  '홍콩(중국 특별행정구)': 'HK'
};
var encindex ={
  AF: 'Afghanistan',
  AX: 'Åland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  VG: 'British Virgin Islands',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  BQ: 'Caribbean Netherlands',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  CD: 'Democratic Republic of the Congo',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands',
  FO: 'Faroe Islands',
  FM: 'Federated States of Micronesia',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  CI: 'Ivory Coast',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  XK: 'Kosovo',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Laos',
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macau',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  KP: 'North Korea',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestine',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn Islands',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russia',
  RW: 'Rwanda',
  SH: 'Saint Helena',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'São Tomé and Príncipe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  KR: 'South Korea',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SZ: 'Eswatini',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syria',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UM: 'United States Minor Outlying Islands',
  VI: 'United States Virgin Islands',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VA: 'Vatican City',
  VE: 'Venezuela',
  VN: 'Vietnam',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe'
};

function swap(json){
  var ret = {};
  for(var key in json){
    ret[json[key]] = key;
  }
  return ret;
}
var revEN = swap(encindex);
$("#myB1tn").click(function(){
        var str = $("#myInput").val();
        var cid = revEN[str];

        if (cid ==undefined) {
          alert("Can't find such country name. Please spell or Capitalize correctly (ex: United States). ");
        } else if(str=="China"){
           alert(`Please check the page on 'Entry Restriction of China' below.`);
        } else{
          var name =  $('#'+cid ).data('name');
          var banDetail= $('#'+cid ).data('ban');
         alert(`Currently, in ${str}, \'${banDetail}\' is in effect.`);
        }


    });


$('.china_path').hover(function(e) {
   $('#info-box').css('display','block');
   var name =  $(this).data('info');
   var banDetail=$(this).data('ban');

   var html = `<h2>${name}</h2><hr style=" border-width: 4px;">
   <div>
   <br><p style= "font-size : 10px;">Current Policy:${banDetail}</p></div>`;

   $('#info-box').html(html);

 });



 $('.china_path').mouseleave(function(e) {
 $('#info-box').css('display','none');
});

    $('.world_path').dblclick(function(e) {
    window.open( $(this).data('web') ,"_self");
  })
  $('.world_path').hover(function(e) {
    $('#info-box1').css('display','block');
    if(!encindex[cindex[$(this).data('name')]]){
      console.log($(this).data('name'));
    }
    var name =  encindex[cindex[$(this).data('name')]];
    var banDetail=$(this).data('ban');
    var html = `<h2>${name}</h2><hr style=" border-width: 4px;">
    <div>
    <br><p style= "font-size : 10px;">Current Policy:${banDetail}</p></div>`;
    $('#info-box1').html(html);

  });


  $('.world_path').mouseleave(function(e) {
  $('#info-box1').css('display','none');
});

  $("#chinh").mousemove(function(e) {
  $('#info-box').css('top',e.pageY-$('#info-box').height()-30);
  $('#info-box').css('left',e.pageX-($('#info-box').width())/2);
}).mouseover();
  $("#map").mousemove(function(e) {
  $('#info-box1').css('top',e.pageY-$('#info-box1').height()-30);
  $('#info-box1').css('left',e.pageX-($('#info-box1').width())/2);
  }).mouseover();
